// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelfHostSekai.Data;

#nullable disable

namespace SelfHostSekai.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331143649_AddCharacterCostume3D")]
    partial class AddCharacterCostume3D
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SelfHostSekai.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AutoLive")
                        .HasColumnType("jsonb");

                    b.Property<string>("Avatar")
                        .HasColumnType("jsonb");

                    b.Property<string>("BoostInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("ChallengeLivePlayDay")
                        .HasColumnType("jsonb");

                    b.Property<string>("CharacterMissionStatuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CharacterMissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CharacterProfileEpisodeStatuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<string>("Currency")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentDeckNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EventBreakTime")
                        .HasColumnType("jsonb");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Profile")
                        .HasColumnType("jsonb");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Shops")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SpecialEpisodeStatuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<string>("TutorialInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("UnitEpisodeStatuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UnreadTopics")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ViewableAppeal")
                        .HasColumnType("jsonb");

                    b.Property<int>("VirtualCoin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserArea", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("ActionSets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AreaItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AreaId");

                    b.ToTable("UserAreas");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserCard", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultImage")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MasterRank")
                        .HasColumnType("integer");

                    b.Property<int>("SkillExp")
                        .HasColumnType("integer");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialTrainingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSkillExp")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CardId");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserCharacter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Costumes3Ds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("UserCharacter");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserDeck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int>("Member1")
                        .HasColumnType("integer");

                    b.Property<int>("Member2")
                        .HasColumnType("integer");

                    b.Property<int>("Member3")
                        .HasColumnType("integer");

                    b.Property<int>("Member4")
                        .HasColumnType("integer");

                    b.Property<int>("Member5")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDecks");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserItem", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ItemType", "ItemId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserMusic", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VocalId")
                        .HasColumnType("integer");

                    b.Property<int>("MusicId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "VocalId");

                    b.ToTable("UserMusics");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserMusicResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HighScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllPerfect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullCombo")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("MusicDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("MusicId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayType")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMusicResults");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserUnlock", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnlockAt")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "Category", "ItemId");

                    b.ToTable("UserUnlock");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserArea", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Areas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserCard", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserCharacter", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserDeck", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserItem", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserMusic", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Musics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserMusicResult", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("MusicResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.UserUnlock", b =>
                {
                    b.HasOne("SelfHostSekai.Models.User", "User")
                        .WithMany("Unlocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfHostSekai.Models.User", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Cards");

                    b.Navigation("Characters");

                    b.Navigation("Decks");

                    b.Navigation("Items");

                    b.Navigation("MusicResults");

                    b.Navigation("Musics");

                    b.Navigation("Unlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
